# Generated by Django 6.0.1 on 2026-01-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hn_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('points', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('content_text', models.TextField(blank=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank', '-points'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('model_name', models.CharField(default='local-gpu', max_length=200)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='news.article')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
